#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Please read the instructions at
https://marketplace.digitalocean.com/apps/rstudio

If you have questions, please send me a tweet. My Twitter username
is @pachamaltese.

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
